package:
  name: "coastalimagelib"
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/mailemccann/CoastalImageLib

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - imageio
    - matplotlib
    - numpy
    - opencv
    - jupyter
    - ipykernel
    - scikit-image
    - scipy
    - scikit-image
    - scikit-learn
    - netCDF4
    - multiprocess
    - xarray

about:
  home: https://github.com/mailemccann/CoastalImageLib
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Python toolbox for creating coastal image products and image preprocessing."

extra:
  recipe-maintainers:
    - mailemccann